---
- name: check v2ray existence
  stat:
    path: /usr/local/bin/v2ray
  register: v2ray_stat

- name: download v2ray installer
  get_url:
    url: https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh
    dest: /tmp/install-release.sh
    mode: '755'
    force: true
  when: not v2ray_stat.stat.exists

- name: download v2ray dat installer
  get_url:
    url: https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-dat-release.sh
    dest: /tmp/install-dat-release.sh
    mode: '755'
    force: true
  when: not v2ray_stat.stat.exists

- name: execute the v2ray installer
  command: "/tmp/install-release.sh --version {{ v2ray_version }}"
  when: not v2ray_stat.stat.exists

- name: execute the v2ray dat installer
  command: "/tmp/install-dat-release.sh"
  when: not v2ray_stat.stat.exists

- name: remove the v2ray installer
  file:
    path: /tmp/install-release.sh
    state: absent
  when: not v2ray_stat.stat.exists

- name: remove the v2ray dat installer
  file:
    path: /tmp/install-dat-release.sh
    state: absent
  when: not v2ray_stat.stat.exists

- name: enable v2ray service
  service:
    name: v2ray
    state: started
    enabled: true
  when: not v2ray_stat.stat.exists

- name: check v2ray configuration existence
  stat:
    path: /usr/bin/v2ray
  register: config_stat

- name: create v2ray config
  file:
    state: touch
    path: /usr/local/etc/v2ray/config.json
    mode: '644'
  when: not config_stat.stat.exists

- name: v2ray config test
  command:
    cmd: /usr/local/bin/v2ray -test -config=/usr/local/etc/v2ray/config.json
  changed_when: false
  notify: restart v2ray service
